name: testapp
description: "A new Flutter project."

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.3
  get: ^4.7.3
  url_launcher: ^6.3.2
  flutter_easyloading: ^3.0.5
  intl: ^0.20.2
  logger: ^2.6.2
  carousel_slider: ^5.1.1
  smooth_page_indicator:
  shared_preferences:
  video_player: ^2.9.1
  webview_flutter: ^4.13.1
  share_plus: ^10.0.0
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.27
  image_picker:
  http_parser:



dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
